controllers/SiteController.php
<?php

namespace app\controllers;

use app\models\UserModel;
use Yii;
use yii\filters\AccessControl;
use yii\web\Controller;
use yii\filters\VerbFilter;
use app\models\LoginForm;
use app\models\ContactForm;
use PhpOffice\PhpWord\PhpWord;

class SiteController extends Controller
{
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'only' => ['logout'],
                'rules' => [
                    [
                        'actions' => ['logout'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'logout' => ['post'],
                ],
            ],
        ];
    }

    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
            'captcha' => [
                'class' => 'yii\captcha\CaptchaAction',
                'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null,
            ],
        ];
    }

    public function actionIndex()
    {
        return $this->render('index');
    }

    public function actionLogin()
    {
        if (!\Yii::$app->user->isGuest) {
            return $this->goHome();
        }

        $model = new LoginForm();
        if ($model->load(Yii::$app->request->post()) && $model->login()) {
            $this->redirect(['book/index']);
        } else {
            return $this->render('login', [
                'model' => $model,
            ]);
        }
    }

    public function actionLogout()
    {
        Yii::$app->user->logout();
        return $this->goHome();
    }

    public function actionRegister() {
        $mUser = new UserModel();
        if($mUser->load(Yii::$app->request->post()) && $mUser->save()){
            //авторизуем пользователя
            $mLoginForm = new LoginForm();
            $mLoginForm->username = $mUser->username;
            Yii::$app->user->login($mLoginForm->getUser(), 3600*24*30);
            $this->redirect(['book/index']);
        } else {
            return $this->render('register', ['mUser' => $mUser]);
        }
    }

    public function actionTestWord(){

        $phpWord = new PhpWord();

        $template = $phpWord->loadTemplate("img/test.docx");

        $template->setValue("name", "Ivan");

        $template->saveAs("img/newtest.docx");

        echo "done!";
    }

}

views/layouts/main.php
<?php
use app\assets\KurentoAsset;
use yii\helpers\Html;
use yii\bootstrap\Nav;
use yii\bootstrap\NavBar;
use yii\widgets\Breadcrumbs;
use app\assets\AppAsset;

/* @var $this \yii\web\View */
/* @var $content string */

AppAsset::register($this);

?>
<?php $this->beginPage() ?>
<!DOCTYPE html>
<html lang="<?= Yii::$app->language ?>">
<head>
    <meta charset="<?= Yii::$app->charset ?>">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <?= Html::csrfMetaTags() ?>
    <title><?= Html::encode($this->title) ?></title>
    <?php $this->head() ?>
</head>
<body>

<?php $this->beginBody() ?>
    <div class="wrap">
        <?php
            NavBar::begin([
                'brandLabel' => Yii::t('app','Book Manager'),
                'brandUrl' => Yii::$app->homeUrl,
                'options' => [
                    'class' => 'navbar-inverse navbar-fixed-top',
                ],
            ]);
            $items = [
                ['label' => \Yii::t('app', 'Главная'), 'url' => ['/site/index']],
                Yii::$app->user->isGuest ?
                    ['label' => \Yii::t('app', 'Регистрация'), 'url' => ['/site/register']] :
                    ['label' => \Yii::t('app', 'Книги'), 'url' => ['/book/index']],
                Yii::$app->user->isGuest ?
                    ['label' => \Yii::t('app', 'Логин'), 'url' => ['/site/login']] :
                    ['label' => \Yii::t('app', 'Выход') . '(' . Yii::$app->user->identity->username . ')',
                        'url' => ['/site/logout'],
                        'linkOptions' => ['data-method' => 'post']],
            ];
            if(!Yii::$app->user->isGuest){
                $items[] = ['label' => \Yii::t('app', 'Консультации'), 'url' => ['/consultation']];
            }
            echo Nav::widget([
                'options' => ['class' => 'navbar-nav navbar-right'],
                'items' => $items
            ]);
            NavBar::end();
        ?>

        <div class="container">
            <?= Breadcrumbs::widget([
                'links' => isset($this->params['breadcrumbs']) ? $this->params['breadcrumbs'] : [],
            ]) ?>
            <?= $content ?>
        </div>
    </div>

    <footer class="footer">
        <div class="container">
            <p class="pull-left">&copy; <?= \Yii::t('app', 'Book Manager') ?> <?= date('Y') ?></p>
            <p class="pull-right"><?= Yii::powered() ?></p>
        </div>
    </footer>

<?php $this->endBody() ?>
</body>
</html>
<?php $this->endPage() ?>